### ISSUE TITLE
Filtering fails on last letter

### ISSUE THREAD

**Issue by hoppfrosch** [DrorHarari/keypirinha-rdp#2]
Situation:  I have opened a RDP connection to computer  MCCOY previously. Now I want to reopen the RDP connection via Keypirinha-rdp again.

How to reproduce:
* Open Keypirinha
* Start typing:
    MCCO   ->  "Connect to mccoy.xxxx.com as domain\user" is on top of the keypirinha list
* Type last letter: "Y"
    MCCOY -> Another random entry from keypirinha list jumps on top of the list (in my case: "msvccompiler.py"
   => "Connect to mccoy.xxxx.com as domain\user" is only on second place of the list
(HINT: "mccoy" as keyword in keypirinha is the only 100% match to stored RDP-connection ...)

What I would expect:
* Having a perfect match in Keypirinha (I typed "MCCOY"), the best match offered in keypirinha should be "MCCOY" and not (in the example above) "msvccompiler.py" 
"MCCOY" is only an example - the same behaviour is on each stored RDP-connection

This is annoying, as you cannot simply press "return" in keypirinha to open the RDP connection after entering RDP connection to match completely.

**Comment by DrorHarari** [comment]
Hi Hopp. I am with you 100% but I don't think I can fix this from an extension -- the extension provides KP with its suggestions but what KP shows depends on what's being suggested by other plugins and KP's internal logic around this.

I think it would be best if you paste the above text as a query on https://gitter.im/Keypirinha/Keypirinha - maybe someone there have an idea (e.g., KP's author).

Dror

p.s. I am closing this issue - in case you think I'm wrong, let me know why. Thanks.
